### ISSUE TITLE
run train.py failed

### ISSUE THREAD

**Issue by sunbin1205** [yuwenhuisama/NumberedImageComparation#1]
thanks for your shared!
when i run train.py error occured as this: 
 File "/media/Linux/sun/NumberedImageComparation-master/resource.py", line 45
    nonlocal full_width, full_height, count
                      ^
SyntaxError: invalid syntax

but i haven't change the code !what's wrong?

**Comment by yuwenhuisama** [comment]
Hi, keyword `nonlocal` can only be used in python3, so I think you should change you version of python to run this project.
