### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by sunbin1205** [yuwenhuisama/NumberedImageComparation#2]
I would like to use your network to train my own data sets.  Do you have any format requirements for the dataset? Urgent please! Thank you very much!

**Comment by sunbin1205** [comment]
我制作的数据集训练时出现了如下错误：
3
3
3
1
Traceback (most recent call last):
  File "train.py", line 42, in <module>
    network.train(episode, batch_size)
  File "/media/Linux/sun/NumberedImageComparation-master/network.py", line 149, in train
    self.dataset.load_dataset()
  File "/media/Linux/sun/NumberedImageComparation-master/resource.py", line 97, in load_dataset
    self.lookup_dataset_dir(dummy)
  File "/media/Linux/sun/NumberedImageComparation-master/resource.py", line 170, in lookup_dataset_dir
    callback(self, dir, file)
  File "/media/Linux/sun/NumberedImageComparation-master/resource.py", line 84, in dummy
    if int(splittext[2]) == 1:
IndexError: list index out of range
help，thanks！

**Comment by yuwenhuisama** [comment]
Hi, the format of dataset is simpy, for example, if you have a set of pictures to compare to each other such as `1.png, 2.png, ..., n.png`,
then you should put them together into a folder, and create a file named `dataset.txt`, every line in this file is listed such as:

>1.png/t2.png/t0or1
>1.png/t3.png/t0or1
>...

where 0 shows these two pictures is not the same, and 1 shows they are same.

Puth this forlder under `Pic/` folder and try training and you'll get the result.

Hope this can help you and sorry for answer late. ^_^

**Comment by sunbin1205** [comment]
I am very glad to receive your reply, but I have a problem with my training process.
I trained with GeForce GTX 1080 Ti gpu, i set turn 80and epoch 128 ，but I was confused by such mistakes after several rounds of training.it failed after only turn4，why？？can you help me??thanks!
Epoch 7/10
128/128 [==============================] - 1s - loss: 0.1700 - acc: 0.9375
Epoch 8/10
128/128 [==============================] - 1s - loss: 0.0309 - acc: 0.9922
Epoch 9/10
128/128 [==============================] - 1s - loss: 0.2694 - acc: 0.9453
Epoch 10/10
128/128 [==============================] - 1s - loss: 0.1638 - acc: 0.9375
Turn 4 :
TIFFReadDirectory: Incorrect count for "SampleFormat".
TIFFReadDirectory: Incorrect count for "SampleFormat".
Traceback (most recent call last):
  File "train.py", line 42, in <module>
    network.train(episode, batch_size)
  File "/media/Linux/sun/NumberedImageComparation-master/network.py", line 154, in train
    data, labels = self.dataset.next_batch(batch_size)
  File "/media/Linux/sun/NumberedImageComparation-master/resource.py", line 201, in next_batch
    pos_data = list(map(self.get_image_data, org_pos_data))
  File "/media/Linux/sun/NumberedImageComparation-master/resource.py", line 177, in get_image_data
    newimg1 = np.array(scm.imresize(image1, (STD_HEIGHT, STD_WIDTH)))
  File "/home/zbw/anaconda2/envs/P3/lib/python3.5/site-packages/numpy/lib/utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "/home/zbw/anaconda2/envs/P3/lib/python3.5/site-packages/scipy/misc/pilutil.py", line 554, in imresize
    im = toimage(arr, mode=mode)
  File "/home/zbw/anaconda2/envs/P3/lib/python3.5/site-packages/numpy/lib/utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "/home/zbw/anaconda2/envs/P3/lib/python3.5/site-packages/scipy/misc/pilutil.py", line 326, in toimage
    raise ValueError("'arr' does not have a suitable array shape for "
ValueError: 'arr' does not have a suitable array shape for any mode.
By the way,what is  name of your network?Do you have a paper on this network? I need to study its principles.

**Comment by sunbin1205** [comment]
I am glad to receive your reply so soon!
But I'm sorry, I don't think the size problem is the cause of the problem.
Because I'm going to run the same error on the gpu even if you set it to your original size.
However, if I run on the CPU, no size error will occur, I can run successfully!
I have one more question is that to  the setting of the threshold value of 0.5, when I set to 0.5 the results are all same, when I set to 0.9, the results are all  not  same, please could you make a simple narrative with me of your network to realize the principle of similarity criterion, thank you very much!!!!!

**Comment by yuwenhuisama** [comment]
Hi, I just have recalled a possible problem of yours which may be caused by the number your picture's channels.

Defautly I process the channel of sample pictures as **3 channels**,  and if the picture doesn't have only 3 channels,  error may happen. Can you have a check of your picture's channels?

In my opinion, the output of network is just to measure **how close the output value is to 0/1**. My lables of sample are all '0/1', and I train the network to output a value to approximate whether it's close to 0 (if 2 pictures seem not to be same) or 1(if 2 pictures input seem to be same).

In output, I simiply compare it with 0.5, when output is largger than middle probability **0.5** then I determined **the 2 pictures input may be same** otherwise **the 2 pictures input may not be same**.

Of course,  **0.5** may not be the greatest threshold when training, and you can modify it to be more strict such as 0.7 or largger (But I think you need much more epochs and samples to traing).

**Comment by sunbin1205** [comment]
oh，thanks for your share.but i think you haven't understand my question;
first,the train code can run successfuly by cpu thought the pic data is with 32 deepth.but I cahnged input_shape = (STD_HEIGHT, STD_WIDTH, 6) to input_shape = (STD_HEIGHT, STD_WIDTH, 8),then it worked;but gpu failed with error ValueError: 'arr' does not have a suitable array shape for any mode awayes
second,though use cpu train the network is so slow,i got the model file,however!butbutbut!!the file seem to predict any pic with same result ,such as: [[0.8118684]] Same.when test two same pic or two different picture!!what is the real question!look foward your help!thanks ^_^

**Comment by sunbin1205** [comment]
oh，thanks for your share.but i think you haven't understand my question;
 first,the train code can run **successfuly by cpu** thought the pic data is with 32 deepth.but I cahnged input_shape = (STD_HEIGHT, STD_WIDTH, 6) to input_shape = (STD_HEIGHT, STD_WIDTH, 8),then it worked;**but gpu failed** with error ValueError: 'arr' does not have a suitable array shape for any mode awayes
 second,though use cpu train the network is so slow,i got the model file,however!butbutbut!!the file seem to predict **any pic with same result** ,such as: [[0.8118684]] Same.when test two same pic or two different picture!!what is the real question!look foward your help!thanks ^_^

**Comment by yuwenhuisama** [comment]
Hi, your problem is so wired and can you send your dataset to me for testing?
My email is yuwenhuisama@outlook.com
Thanks! ^_^

**Comment by sunbin1205** [comment]
I'm sorry to true the email late.
I have solved the problem of my  data set running on GPU.
But there is a little bit of trouble in the predict process!
For example, I'm now testing four charts.
Figure 1 and figure 2 are the same, and the test result is same, no problem!
Figure 3 and figure 4 are the same, and the test result is same, and no problem!
However, I use figures 1 and 4 to test (they must be different) but the result is the same!
I hope this can be the last error for me to solve!maybe you know why?
